### ISSUE TITLE
using eachRow() and stream() methods

### ISSUE THREAD

**Issue by dhavalocked** [dtoubelis/sails-cassandra#39]
hi, how can i select more number of rows then defined fetch size? cassandra dataStax dev site suggest to use stream or eachRow method with setting autoPage flag true.  [link](http://datastax.github.io/nodejs-driver/#paging) .

so is there anyway i can use existing sails-cassandra module to fetch data from large tables?

**Comment by dtoubelis** [comment]
You most likely should be able to use `.stream()` method from sails/waterline. It was implemented long time ago and there should be a test case for it in `test` directory. 

For other methods it is complicated. First of all Waterline ORM provides some abstract data model based on relational databases and MySQL in particular. This set of abstraction somewhat maps to a subset of cassandra features. The README page for the project outlines all these mappings in great details.

I think what is relevant to your case would be using `skip` and `limit` query options. Unfortunately, I was only able to implement `limit`. `skip` was not supported in v2.x driver and I did not have an opportunity to explore if situation is any different in v3.x. I may give it another look, but I'm quite busy at the moment and it may take awhile (especially given the dying state of the project).

One thing to keep in mind (and this is my understanding based on v2 of Cassandra) that pagination only works on naturally ordered data, i.e. data from a single big row. Otherwise, you may get different results on subsequent queries. So, whether or not you can do pagination also depends on your data model. So, even if this feature somehow available in the driver it may not work as expected.

What would help though, if you could provide a sample of your model and query using DataStax's driver that works the way you expect. Then I can see if it can be done in sails/waterline universe.

**Comment by mrwhite1** [comment]
thanks for the reply, the case is lets say you have to select some rows based on a criteria.  and the number of rows satisfying that criteria is more than the max fetch size limit. in this case you will bee able to fetch only some rows and not all based on your fetch size limit. and yeah i gave a look at `.stream()` method and `.eachRow` mthod. 

what i am doing now is the i have changed the small portion of code in `.query()` method in collection.js file. 

`if (_.isString(queries)) {
    // execute query
    // this.client.execute(queries, params, { prepare: true }, function(err, result) {
    //   if (err) return cb(err);
    //   cb(null, result.rows);
    // });
    // get results
    var results = [];

    this.client.stream(queries, params, { prepare: true, autopage: true })
    .on('readable', function () {
      var row;
        while (row = this.read()) {
        results.push(row);
        }
      })
      .on('end', function () {
          cb(null, results);
      })
      .on('error', function (err) {
        return cb(err);
    });
  }`

and using the `.stream()` method i can now retrieve all the rows irrespective of fetch size limit. is there any drawback of this method?

**Comment by dtoubelis** [comment]
If `.stream()` works for you then this is the way to go. Streaming is still encouraged pattern in node.js community and it works quite well if done properly.

The only drawback I can think of is if you need the actual pagination and you whant ro retrieve page 48 out of 100. In that case you will be pulling and discarding first 47 pages since there is no way to skip to the beginning of page 48. If this is not your case then go with the `.stream()` 👍 

Note, that I'm not up to date on cassandra development and I haven't touched it since this adapter was written few years ago, so take my opinions with a grain of salt.

Let me know if this addresses your issue and I can close the ticket.

**Comment by mrwhite1** [comment]
for now i am fine with `.stream()` (the code i shared) but i will give it a try based on test case. Thanks for the reply :) 👍

**Comment by mrwhite1** [comment]
Hi, reopen this issue as i have a doubt, how can i use `.stream()` method for streaming a response ? like if i have used a model.query method than how can i stream the response of that query?
